apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "app1.fullname" . }}-backend
  labels:
    app: {{ template "app1.name" . }}-backend
    chart: {{ template "app1.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "app1.name" . }}-backend
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app1.name" . }}-backend
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: # maybe 3000
              protocol: # maybe TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: # maybe 30
            periodSeconds: # maybe 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: # maybe 10
            periodSeconds: # maybe 30
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
{{ toYaml .Values.image.backend.env | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}