apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app1.fullname" . }}-secrets
  labels:
    chart: {{ template "app1.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

type: Opaque
data:
  DatabaseUrl: {{ .Values.secrets.DatabaseUrl  | b64enc }}
  SecretKey: {{ .Values.secrets.SecretKey  | b64enc }}
  # other secrets can be addedd here
  